### ISSUE TITLE
Astronomy data is incorrect

### ISSUE THREAD

**Issue by aproposnix** [kylecorry31/Trail-Sense#1619]
I'm living in Czechia, and on the app it gives different times for the daylight hours, sunset and sunrise as compared to (for example): 

- https://www.worlddata.info/europe/czechia/sunset.php or
- https://dateandtime.info/citysunrisesunset.php?id=3067696

Or, am I just not seeing some simple explanation? 

Love this app btw. thanks for making it. 

EDIT: Spoke to some other people about this, it's complicated but it's very possible to see these discrepancies in timing.  So, TIL something :) 

This ticket should be closed.

**Comment by kylecorry31** [comment]
I checked this in my emulator, and it was only a couple minutes different from those websites - and it matched a few others.

I normally use this website in my testing, and it tends to match perfectly: https://www.timeanddate.com/sun/czech-republic/prague

It appears that Trail Sense is not factoring in atmospheric refraction (which is why the times are a little different) - I can't remember if I did this on purpose, or if I accidently have it turned off. I've created this issue to track that: https://github.com/kylecorry31/Trail-Sense/issues/1620
