### ISSUE TITLE
Not displaying meteor showers

### ISSUE THREAD

**Issue by naoliv** [kylecorry31/Trail-Sense#1740]
A friend sent me a screenshot of his phone:

![](https://user-images.githubusercontent.com/982338/233866028-cd4d0b7b-4e62-4538-98f5-cb0c32b598e9.jpeg)

Although it shows "Location not defined" at the top, it is displaying the Lyrids meteor shower.

However, on my phone, where location is allowed at all times and it's enabled to display meteor showers, I don't see anything in this area:

![a](https://user-images.githubusercontent.com/982338/233866695-3d4ee6ee-c21b-4622-8b9e-e84b3dd4fde4.png)

What could be wrong or what could I be missing here, please?

I am using Trail Sense 4.17.0

**Comment by kylecorry31** [comment]
@naoliv Hi, can you confirm you have the Meteor showers setting enabled under Trail Sense settings > Astronomy?

It appears the peak was yesterday, so you may have to check yesterday instead of today - it will only show for the date of the peak.

Also, it will only show up if it is visible from your location - I don't believe the Lyrids was visible in the southern hemisphere if that's where you are.

If you long press the calendar icon above the chart, you can see the date of the next meteor shower in your area.
