### ISSUE TITLE
Material you color scheme

### ISSUE THREAD

**Issue by MedwardR** [kylecorry31/Trail-Sense#2003]
Incredible app!
Material you design would be even cooler though.

Something like this:
![ResizedImage_2023-10-20_21-01-05_1.png](https://github.com/kylecorry31/Trail-Sense/assets/117788102/2e47a897-5d5e-490f-ae3b-40ceb46eaf0f)

**Comment by kylecorry31** [comment]
Thank you for the suggestion - I'm going to close this out in favor of https://github.com/kylecorry31/Trail-Sense/issues/1008

The support for Material You (Dynamic Colors) exists in Trail Sense but wasn't enabled because I need to do a lot of testing to ensure the colors work with all the tools. Unfortunately, I haven't had the time to do that and this has stayed lower in my priority list as I work to build out other features. I'll try to bundle this with some of the other UI changes I'm making this year.
