### ISSUE TITLE
Samsung Dynamic Color not correctly applying theme color

### ISSUE THREAD

**Issue by WildManiac** [kylecorry31/Trail-Sense#2179]
The Dynamic Color setting is not applying the correct theme color when enabled.

| On Device Theme Color | Dynamic Color in App |
|---|---|
|![Screenshot_20240124_100646_Wallpaper and style](https://github.com/kylecorry31/Trail-Sense/assets/11233971/2127efa3-7f3b-475d-8619-a816e0e939ed)|![Screenshot_20240124_100710_Trail Sense](https://github.com/kylecorry31/Trail-Sense/assets/11233971/1b57cf07-36bd-43e1-adf0-42140b20a433)|

Trail Sense Version: 5.7.1-dev
Device: Samsung Galaxy A52 5G
Operating System: OneUI 6.0 (Android 14)

Please let me know if any other information is needed.

**Comment by WildManiac** [comment]
"Most" of the apps that I have that have Dynamic Color configuration do respect the purple-ish color pallette. Below is what it looks like in Barcode Scanner:

![Screenshot_20240124_111349_Barcode Scanner](https://github.com/kylecorry31/Trail-Sense/assets/11233971/97764bae-1e09-4da8-b99e-d2226d3abbcb)

Granted, Trail Sense isn't the first app that I have run into that doesn't apply the color pallette correctly, so I don't know if it is an app thing or a Samsung thing. But yeah, I can certain run a nightly whenever it is available.

**Comment by kylecorry31** [comment]
I just tested in the Samsung remote lab, and it does respect the "Basic colors" theme just fine, but when you use "Wallpaper colors" it always uses the color in the middle as the primary color. I suspect there are other apps that do the same thing because that's the out of the box behavior with the Google Material library that's recommended. I'll do more investigation to see if I can make it use the top color in the wallpaper colors. 

I'll post here when a nightly fix is available.

**Comment by WildManiac** [comment]
That is interesting, because no matter what colors I select, whether it be Wallpaper or Basic, Trail Sense still has the default blue theme when Dynamic Colors is enabled.

**Comment by kylecorry31** [comment]
Hm, I tested on an Android 13 Samsung device, so maybe it's different across versions

**Comment by kylecorry31** [comment]
Developer notes:

Looks like this is an upstream issue on the Google Material 3 library: https://github.com/material-components/material-components-android/issues/3924

Some people suggest downgrading to version 1.10.0 - I need to research the differences before I downgrade

**Comment by kylecorry31** [comment]
@WildManiac a new nightly build is available with a fix for this (tested via the samsung remote device lab): https://github.com/kylecorry31/Trail-Sense/actions/runs/7647008723

Unfortunately, the issue was upstream in the Google Material library and I had to downgrade it to fix it. Unfortunately, I suspect until that is fixed more apps are going to start having this issue as they upgrade to the latest version.

**Comment by WildManiac** [comment]
I can confirm that Dynamic Color is reflecting appropriately on my device.

![Screenshot_20240125_082500_Trail Sense](https://github.com/kylecorry31/Trail-Sense/assets/11233971/2156c6e3-ca0e-4a6a-8033-183f729c90dd)

And per your comment about other apps seeing this issue, that might be why I have some that don't reflect the appropriate color.

**Comment by kylecorry31** [comment]
Thank you for testing that! I'll roll out a new release this weekend with the fix.

**Comment by kylecorry31** [comment]
I'm going to be upgrading the material library in the next release, which Google recommends. They claim Samsung fixed the issue in their OS updates, though devices that haven't updated will have this issue still (I suspect most updated since this impacted all material you apps, including Google's).

I figured a year an a half is long enough, and this will allow me to consume the latest material features.
