### ISSUE TITLE
Metronome

### ISSUE THREAD

**Issue by GuiSousa135** [kylecorry31/Trail-Sense#2495]
It would be very useful to have a simple metronome in the Trail Sense toolbox, with the basic functions of selecting BPM, modifying the tempo, sound and vibration, among other functions.

Although it seems outside the project's initial proposal, I believe it would be very welcome to the app, as well as QR Code Scanner, Mirror Camera, Ruler, etc.

A metronome is an easy-to-implement function and can be used in a variety of situations, mainly for playing instruments on trails and camping trips.

Example of an excellent open source metronome project with Material Design: https://github.com/patzly/tack-android

**Comment by kylecorry31** [comment]
Hi, I'm curious if there are any use cases for this outside of music related to hiking/camping?

Unfortunately, if this is just for music, then I will likely not implement this since I believe it is out of scope of Trail Sense's use cases (I see music + camping as two different activities that can occur at the same time). But I will potentially consider linking that in the recommended apps guide if there are other use cases.

**Comment by kylecorry31** [comment]
Thank you, I will take a look at those other use cases later and see if they fit into Trail Sense. If not, then I would suggest using the open source app you mentioned.

While simple to implement, I don't want to increase the scope of Trail Sense to be a generic tool app, so am a bit picky on what tools get added.

**Comment by kylecorry31** [comment]
After further research, I've decided not to implement this in Trail Sense. But I can link to that metronome app as a recommended tool for camp music.
