### ISSUE TITLE
Barcode scanner

### ISSUE THREAD

**Issue by GuiSousa135** [kylecorry31/Trail-Sense#2544]
add a simple barcode scanner (as the qrcode scanner function)

**Comment by kylecorry31** [comment]
@GuiSousa135 hi, can you specify what purpose this would have under the Trail Sense [use cases](https://github.com/kylecorry31/Trail-Sense/wiki/Use-Cases)?

When creating the QR code scanner, I did not add barcode support because I don't see them used on trails, and typically without a barcode database (requires internet access), they are not very useful.

**Comment by kylecorry31** [comment]
Thank you for the clarification - in that case, I am not going to implement this since I believe it to be out of scope. If a use case comes up that meets Trail Sense's core use cases, I will be happy to reconsider.
