### ISSUE TITLE
App begins to lag after a while of use

### ISSUE THREAD

**Issue by An-anonymous-coder** [kylecorry31/Trail-Sense#2579]
I have checked for duplicates of this issue, but did not find any. The app was installed via the APK file on the releases page (6.3.0-dev). My device is a Pixel 8 running GrapheneOS.

After using the app for a while (a couple weeks) it will begin to show significant signs of lag. The compass will not turn smoothly, no menus will scroll smoothly, etc. The only way to fix this issue is to clear the app storage, and if I import a recovery file of my settings it will begin to lag again. I have to manually reconfigure the settings instead of importing them to prevent the lagging. 

There are no errors, the issue is present even with location and sensor permissions disabled, I have tried clearing the cache and resetting calibration, nothing else works but resetting the app entirely. 

I don't know how to reproduce this other than to just use the app normally. I would be happy to privately provide the recovery file for my data for testing purposes.

**Comment by kylecorry31** [comment]
@An-anonymous-coder hi, I have not experienced this before.

My suspicion is that you may have Backtrack always on (Settings > Paths > Backtrack) and the backtrack history set to a large number (Settings > Paths > Backtrack history) or the path marked as keep forever (Tools > Paths > there may be a path that has dates as the title, if it is temporary it will display "Temporary" in the list). 

If you are fine sending the recovery file, you can email it to me at trailsense@protonmail.com

**Comment by kylecorry31** [comment]
Thank you for the further information. I'm still not 100% sure what it can be.

I will say that the dev versions of the app have debug mode enabled which can cause lag that isn't present on the builds posted on F-Droid and Google Play.

Clearing storage should wipe all settings and data, so I don't think it's the accumulation of data from Trail Sense itself. Because of that, I'm leaning toward the debug build being the problem. Since I actively develop Trail Sense, I don't think I've gone more than a week without reinstalling the debug build (but have gone longer than a month with the release build without issue).

**Comment by kylecorry31** [comment]
Glad that helped.

Here's an issue to track the release build on GitHub releases: https://github.com/kylecorry31/Trail-Sense/issues/2580

As for the slight stutter on that page, that is a known issue and I will eventually fix that here: https://github.com/kylecorry31/Trail-Sense/issues/1771

(should be a lot less than the debug build though - debug builds on Android have pretty poor performance, especially on newer versions of Android for some reason)

**Comment by kylecorry31** [comment]
I'm going to close this for now, but if the compass lag begins again, just let me know and I'll reopen this
