### ISSUE TITLE
Loudly alert user when cell tower data is received

### ISSUE THREAD

**Issue by notramo** [kylecorry31/Trail-Sense#291]
Cell tower coverage is poor in forests, and valleys. There should be an option, to loudly alert the user when cell tower data is received. This can be used to place an emergency call.

I don't know if it can be done without root.

**Comment by kylecorry31** [comment]
While this is a cool idea, Trail Sense would need to request mobile data / Internet permission - which a lot of people using it may not like. I know many Android phones do support sending a text message when reconnected to data, so that could be a natively supported option. 

Also, you would need some root permissions (or at least elevated permissions) to adjust the user's sound setting to play a loud sound to alert them.
