### ISSUE TITLE
Alternative for phones without a barometer

### ISSUE THREAD

**Issue by gabsoftware** [kylecorry31/Trail-Sense#53]
Lots of devices do not have a pressure sensor. Mine for example (OnePlus 5T) does not have one. It would be nice if in that case we could use an alternative source for pressure monitoring.

For example there is [this API](https://openweathermap.org/current): api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={your api key}

This would require to add at least two settings: the API key and the polling interval.

Alternatively, do not display the weather panel at all if there is no pressure sensor on the phone.

**Comment by kylecorry31** [comment]
Hmm, this is a tough decision, but I am going to have to say that if the phone does not have a barometer, the weather panel will not be displayed. I say this because I want a focus of this app to be that the only data presented comes from the device's sensors and does not use the Internet at all. Therefore, the weather feature will only be available to phone's with barometers - I'll adjust the app accordingly, thanks for pointing this out to me!
