### ISSUE TITLE
Linear compass not working

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#551]
There are some settings (or the features) that require a special sensor. One example: the feature "Show linear compass" is shown on my device, but this feature doesn't work. So it would good to hide the setting.

**Comment by kylecorry31** [comment]
Hmm, what device are you using? The linear compass should work on any device with an accelerometer (basically all phones).

Are you holding your phone vertically while on the navigation tab?

The only two required sensors in Trail Sense are the magnetometer and accelerometer (because the compass uses both of them), which is why settings don't disable for them. The barometer and pedometer disable their respective settings/tools.

**Comment by kylecorry31** [comment]
I'm wondering - so the linear compass uses the gravity sensor (I thought this was available on all devices with an accelerometer), while with the compass itself it uses the gravity and falls back to a custom version on the accelerometer. 

I can make that change for the next release to see if that helps.

**Comment by qwerty287** [comment]
> Hmm, what device are you using? The linear compass should work on any device with an accelerometer (basically all phones).
> 
> Are you holding your phone vertically while on the navigation tab?
> 
> The only two required sensors in Trail Sense are the magnetometer and accelerometer (because the compass uses both of them), which is why settings don't disable for them. The barometer and pedometer disable their respective settings/tools.

I use a HMD Global Nokia 5.3, and it should have both sensors (Trail Senses sensor details confirm this). 
Yes, I hold my phone vertically, but nothing happens.

**Comment by kylecorry31** [comment]
Thanks, I'll make some changes to the linear compass to add the same custom gravity sensor fallback that's being used elsewhere.

**Comment by qwerty287** [comment]
I don't know why, but this doesn't work for me. Maybe it helps you that the inclinometer doesn't work too, it just says "Hold your phone vertically to measure inclination", even if I hold it vertically. I don't know how that's done, but the bubble level tool works fine. Do I have to toggle on a setting in the system's settings?
My phone has gravity sensor is, and it seems to work (the values are correct, I'd say)

(I wasn't sure if this should be fixed in 2.1.0 and F-Droid updated to 2.2.0 today)

**Comment by kylecorry31** [comment]
I just checked

**Comment by kylecorry31** [comment]
I just checked and I updated the wrong sensor as a part of this issue... I have the poorly named "DeviceOrientationSensor" and "DeviceOrientation", both of which do different things - I only updated one of them (and couldn't test because my device and emulate both had the gravity sensor). I'll update the core library to account for the other sensor and push that out with the next release.

**Comment by qwerty287** [comment]
That's still not working for me. But the inclinometer works after updating to 2.3.0, but the linear compass doesn't appear if I hold my phone correctly.

**Comment by kylecorry31** [comment]
I'll add more diagnostics to the sensor details tool to help debug this - oddly they are using the same sensor.

**Comment by kylecorry31** [comment]
I just tried on my phone and it isn't working for me anymore. I'll see if I can figure out what changed and put out a hotfix.
