### ISSUE TITLE
Make convert a single tool

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#582]
The tool itself will have multiple tabs or a list of units to convert (which ever is easier). You can select one and it will open the convert screen for that unit - for not just distance and coordinates.

The new convert tool can be placed under the 'Other' section of the tools (first item under the header).

**Comment by qwerty287** [comment]
Hi,
I'm working on this, but I'm not sure if I understood your UI idea. I captured two screenshots, see below. By the way, in my AVD, the distance converter has a wrong format (see the second screenshot), this even happens if you enter something. Is this a bug or another problem?

![Screenshot_1620388712](https://user-images.githubusercontent.com/80460567/117446729-c997cf00-af3c-11eb-8d15-57e5243ee384.png)
![Screenshot_1620388715](https://user-images.githubusercontent.com/80460567/117446732-cb619280-af3c-11eb-919a-1fd43ace8f19.png)

There are still some things that aren't done, I think, the titles in the tab bar should only contain "Coordinates" or "Distance".

**Comment by kylecorry31** [comment]
Yeah, that's what I'm imagining, thanks! And as for the format, that's a work in progress (I just haven't created a new release of TS Core that has the updated formatting yet)

And yes the tabs should only contain coordinates and distance (and also the title under the tabs can go away)
