### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#599]
The README could be improved, I think:

1. There are links to two issues, #71 (feedback to the weather forecasting - issue is closed) and #74 (Debug Builds - the last debug build was for version 0.9 or something around this, if you don't want to package more debug builds, I would remove it from README and close the issue).
2. There is a feature request issue and a discussion - which one is the preferred? If it's the discussion, the link should be changed.

**Comment by kylecorry31** [comment]
Thanks, I'll update it later today. As for the debug builds, I stopped generating them because I wasn't receiving any feedback (I assumed nobody was using them) - I'll change the wording to say if someone wants a debug build to test, to post there and I can create a new one.

Either is preferred, I get notified of both - though people are more familiar with GitHub issues, therefore I left that as the link in the README
