### ISSUE TITLE
Barometer diagram: add min/max

### ISSUE THREAD

**Issue by dennisguse** [kylecorry31/Trail-Sense#69]
At least on the F-Droid version there seems to be no defined min and max for the diagram of the barometric data.
This leads to situations that although there has almost been no change in barometric pressure the diagram looks like there was a big change (in my case 1022 to 1026 only).

Solution: add a lower and upper limit for diagram.

**Comment by kylecorry31** [comment]
Agreed, I actually do have that logic in place, just picked too small of a range

**Comment by kylecorry31** [comment]
How does something like this look?

![Screenshot_20200519-172855](https://user-images.githubusercontent.com/5938560/82380445-76a8cd00-99f6-11ea-942f-153a4bd82d66.png)

**Comment by dennisguse** [comment]
Nice!
According to Wikipedia it usually ranges from 940hPa to 1040hPa on earth. Why not use the full range?
https://en.m.wikipedia.org/wiki/Barometer

**Comment by kylecorry31** [comment]
Using the full range makes it difficult to see smaller, yet meaningful changes and may not be fully accurate when not using sea level pressure. I will experiment with that though.

**Comment by dennisguse** [comment]
i see :)
However, the weather at home is at the moment rather too good for testing ;)

**Comment by kylecorry31** [comment]
I'll put some fake in the UI today and post that later. Looks like there is good weather all week for me too (great for testing the navigation features though!)

**Comment by kylecorry31** [comment]
These screenshots are using data from my local area as a storm approached. I personally prefer either the 20hPa or the 40hPa because they clearly show that the weather is worsening (note: the forecasts in Trail Sense are created via changes in barometric pressure in the 3 hour range for short term forecasting and 48 hours for long term forecast trends, so the user should be able to see the chart matching up with the forecast). In my experience, my local weather varies between about 990 and 1030 hPa typically. 

Range: 20hPa
![Screenshot_1589970312](https://user-images.githubusercontent.com/5938560/82435731-bc9b7a80-9a62-11ea-93a4-a8555f8f09e3.png)


Range: 40hPa
![Screenshot_1589970303](https://user-images.githubusercontent.com/5938560/82435771-c91fd300-9a62-11ea-9bdf-5e1d2430e7d7.png)


Range: 60hPa (normal weather condition variance across earth)
![Screenshot_1589970282](https://user-images.githubusercontent.com/5938560/82435795-d472fe80-9a62-11ea-807e-f5279f7558ac.png)

Range 100hPa (normal atmospheric variance across earth)
![Screenshot_1589970462](https://user-images.githubusercontent.com/5938560/82435963-12702280-9a63-11ea-81c3-6dbb4cb3c134.png)

**Comment by kylecorry31** [comment]
I'm going to close this - if you feel like the new min and max do not address this properly, feel free to reopen.
