### ISSUE TITLE
Add approximate location support

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#972]
This might not be possible when using just the GPS - as far as I can tell the GPS is not available when approximate location is enabled. 

This issue is to research how the approximate location can be supported (and where it would make sense to support it - obviously not on the navigation tab). 

Given the accuracy of coarse location, it would not be suitable for most use cases within Trail Sense. The only tools where it may be enough are the astronomy and climate tools, so it may not be worth adding support.

It might be that this issue would allow approximate location support: https://github.com/kylecorry31/Trail-Sense/issues/432

**Comment by Lee-Carre** [comment]
How about simply querying the `passive` location provider? That way, if other apps (actively) queried for accurate location (e.g. a map navigation app) then this'll be available to TS.

**Comment by kylecorry31** [comment]
Do you have documentation on that / can clarify what you mean? For reference, TS does not use Google Play Services, so uses the native Location class instead

**Comment by Lee-Carre** [comment]
> Do you have documentation on that / can clarify what you mean?

* [Android Location Providers (GPS, Network, Passive)](http://www.developerlife.com/2010/10/20/gps/)
* [Android Developers § LocationManager](http://developer.android.com/reference/android/location/LocationManager)
* [martykan/forecastie#611 (comment)](http://github.com/martykan/forecastie/issues/611#issuecomment-1001077202) (& subsequent comments)

> TS does not use Google Play Services, so uses the native Location class instead

To my limited knowledge of the internals, I think this shouldn't be a problem. I think it's part of Android (the OS) rather than Google Play Services.

I use other apps which I'm pretty sure are free of Play Services, but which use the `passive` location provider.

**Comment by kylecorry31** [comment]
Thanks - I was not aware of this / thought it was a Google Play Services feature, but from the docs it looks like it isn't. I'll consider this when addressing this issue.

**Comment by Lee-Carre** [comment]
See also [android/location-samples](http://github.com/android/location-samples).

**Comment by kylecorry31** [comment]
Not going to implement.

Reasons:
- Frequency of use (ex. edge case) vs effort to implement
- High maintenance burden / likely to cause confusion
- Not technically feasible / will be inaccurate
